apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-kube-demo-production
  annotations:
    cert-manager.io/cluster-issuer: 'prod-issuer-amd64'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - thankyou.kanebroslab.com
    secretName: thanks-prod-tls-v5
  rules:
  - host: thankyou.kanebroslab.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-kube-demo
            port:
              number: 80
